Vagrant.configure(2) do |config|

  config.vm.define "lb1" do |lb1|
    lb1.vm.box = "ubuntu/bionic64"
    lb1.vm.network "private_network", ip: "192.168.2.237"
    lb1.vm.provision "shell", path: "shellscript/lb.sh"
  end

  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/bionic64"
    web1.vm.network "private_network", ip: "192.168.2.238"
    web1.vm.provision "shell", path: "shellscript/web.sh"
  end

  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/bionic64"
    web2.vm.network "private_network", ip: "192.168.2.239"
    web2.vm.provision "shell", path: "shellscript/web.sh"
  end

  config.vm.define "db" do |db|
      db.vm.box = "ubuntu/xenial64"
      db.vm.network "public_network", :bridge => "eth0", ip: "192.168.1.240"
      db.vm.network "forwarded_port", guest: 3306, host: 3306
      db.vm.network "forwarded_port", guest: 80, host: 8306
      db.vm.provision "shell", path: "shellscript/db.sh"
  end
end 