apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: amazonEBS
spec:
  storageClassName: gp2
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-07ac45bacb9575bfa
    fsType: ext4