kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sandbox-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: "amazonEBS"