# Deploy the pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-sandbox-deployment
  namespace: default
  labels:
    app: bbox-sandbox
    env: default
spec:
  selector:
    matchLabels:
      app: d-sandbox
      env: default
  replicas: 1
  template:
    metadata:
      labels:
        app: d-sandbox
        env: default
    spec:
      containers:
      - name: d-sandbox
        image: tuanpembual/sandbox:latest
        imagePullPolicy: Always
        imagePullSecrets:
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: d-sandbox-log
          mountPath: "/log"
          # subPath: "sandbox/default/"
      volumes:
      - name: d-sandbox-log
        persistentVolumeClaim:
          claimName: efs
      - name: registry-secret